'use strict';

const VERSION='0.1.0';
const DB_NAME='naqya-memo-2026';
const DB_VERSION=1;
const ICONS={note:'📝',appointment:'📅',deadline:'⏰',task:'✓',text:'📄',document:'📎',audio:'🎙',dictation:'🎤'};
const LABELS={note:'Notiz',appointment:'Termin',deadline:'Frist',task:'Aufgabe',text:'Textdokument',document:'Dokument',audio:'Audio-Memo',dictation:'Diktat'};
const state={view:'dashboard',entries:[],projects:[],wizardStep:1,wizardType:'note',calendarDate:new Date(),recorder:null,audioChunks:[],dictationRecognition:null,dictationFinal:'',dictationInterim:'',dictationRecorder:null,dictationChunks:[]};
let db;

const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=d=>d?new Intl.DateTimeFormat('de-DE',{dateStyle:'medium',timeStyle:'short'}).format(new Date(d)):'—';
const fmtDate=d=>new Intl.DateTimeFormat('de-DE',{dateStyle:'medium'}).format(new Date(d));
const todayKey=()=>new Date().toISOString().slice(0,10);

function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains('entries')){const s=d.createObjectStore('entries',{keyPath:'id'});s.createIndex('createdAt','createdAt');s.createIndex('type','type');s.createIndex('date','date');s.createIndex('projectId','projectId')}if(!d.objectStoreNames.contains('projects'))d.createObjectStore('projects',{keyPath:'id'});if(!d.objectStoreNames.contains('files'))d.createObjectStore('files',{keyPath:'id'});if(!d.objectStoreNames.contains('settings'))d.createObjectStore('settings',{keyPath:'key'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function store(name,mode='readonly'){return db.transaction(name,mode).objectStore(name)}
function all(name){return new Promise((res,rej)=>{const r=store(name).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(name,value){return new Promise((res,rej)=>{const r=store(name,'readwrite').put(value);r.onsuccess=()=>res(value);r.onerror=()=>rej(r.error)})}
function get(name,key){return new Promise((res,rej)=>{const r=store(name).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function del(name,key){return new Promise((res,rej)=>{const r=store(name,'readwrite').delete(key);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}

async function logEvent(action,entry){const event={id:uid(),type:'chronology',title:action,text:entry?.title||'',createdAt:new Date().toISOString(),date:new Date().toISOString(),meta:{entryId:entry?.id||null,entryType:entry?.type||null},system:true};await put('entries',event)}
async function refresh(){state.entries=(await all('entries')).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));state.projects=await all('projects');render()}

async function seed(){const settings=await get('settings','seeded');if(settings)return;const project={id:uid(),name:'Beispielprojekt',description:'Kann gelöscht oder umbenannt werden.',status:'aktiv',createdAt:new Date().toISOString()};await put('projects',project);await put('settings',{key:'seeded',value:true});await put('settings',{key:'theme',value:'hell'});await put('settings',{key:'scale',value:'standard'});await put('entries',{id:uid(),type:'note',title:'Willkommen bei NAQYA',text:'Speichere schnell. Ordne später. Alles bleibt lokal.',createdAt:new Date().toISOString(),date:new Date().toISOString(),status:'aktiv',priority:'normal',projectId:'',category:'Start',tags:['hilfe'],deleted:false})}

function visibleEntries(){return state.entries.filter(e=>!e.deleted&&!e.system)}
function chronologyEntries(){return state.entries.filter(e=>!e.deleted).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))}
function typeBadge(e){return `<span class="badge ${e.type}">${ICONS[e.type]||'•'} ${LABELS[e.type]||e.type}</span>`}
function entryRow(e){const tags=(e.tags||[]).slice(0,3).map(t=>`<span class="badge">#${esc(t)}</span>`).join('');return `<article class="list-item"><div class="list-icon">${ICONS[e.type]||'•'}</div><div><strong>${esc(e.title||LABELS[e.type]||'Eintrag')}</strong><div><small>${fmt(e.date||e.createdAt)} · ${esc(e.category||'ohne Kategorie')}</small></div><div>${tags}</div></div><div>${typeBadge(e)}</div></article>`}
function pageHead(title,sub,action=''){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div>${action}</div>`}

function renderDashboard(){const entries=visibleEntries();const now=Date.now();const upcoming=entries.filter(e=>e.date&&new Date(e.date).getTime()>=now).sort((a,b)=>new Date(a.date)-new Date(b.date)).slice(0,5);const deadlines=entries.filter(e=>e.type==='deadline'&&e.status!=='erledigt');const today=entries.filter(e=>(e.date||'').slice(0,10)===todayKey());return `${pageHead('Guten Tag','Dein persönlicher Offline-Überblick','<button class="primary" data-quick="note">＋ Schnellnotiz</button>')}<div class="grid dashboard-grid"><section class="card span-3 metric"><div><small class="muted">Heute</small><strong>${today.length}</strong><div>Einträge</div></div><span class="icon">☀️</span></section><section class="card span-3 metric"><div><small class="muted">Offene Fristen</small><strong>${deadlines.length}</strong><div>im Blick behalten</div></div><span class="icon">⏰</span></section><section class="card span-3 metric"><div><small class="muted">Dokumente</small><strong>${entries.filter(e=>['document','text'].includes(e.type)).length}</strong><div>lokal gespeichert</div></div><span class="icon">📄</span></section><section class="card span-3 metric"><div><small class="muted">Projekte</small><strong>${state.projects.length}</strong><div>Arbeitsbereiche</div></div><span class="icon">📁</span></section><section class="card span-8"><h2>Schnell erfassen</h2><div class="quick-grid"><button data-quick="note">📝<span>Notiz</span></button><button data-quick="appointment">📅<span>Termin</span></button><button data-quick="deadline">⏰<span>Frist</span></button><button data-quick="task">✓<span>Aufgabe</span></button><button data-view-go="audio">🎤<span>Diktieren</span></button><button data-view-go="audio">🎙<span>Audio</span></button><button data-quick="document">📷<span>Dokument</span></button><button data-view-go="projects">📁<span>Projekt</span></button></div></section><section class="card span-4"><h2>Nächste Termine & Fristen</h2><div class="list">${upcoming.length?upcoming.map(entryRow).join(''):'<div class="empty">Nichts geplant.</div>'}</div></section><section class="card span-12"><h2>Zuletzt gespeichert</h2><div class="list">${entries.slice(0,6).map(entryRow).join('')||'<div class="empty">Noch keine Einträge.</div>'}</div></section></div>`}

function renderToday(){const entries=visibleEntries().filter(e=>(e.date||'').slice(0,10)===todayKey());return `${pageHead('Heute',fmtDate(new Date()))}<section class="card"><div class="list">${entries.map(entryRow).join('')||'<div class="empty">Heute ist noch nichts eingetragen.</div>'}</div></section>`}
function renderCalendar(){const d=state.calendarDate,y=d.getFullYear(),m=d.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-((first.getDay()+6)%7));const days=[];for(let i=0;i<42;i++){const day=new Date(start);day.setDate(start.getDate()+i);const key=day.toISOString().slice(0,10);const ev=visibleEntries().filter(e=>(e.date||'').slice(0,10)===key).slice(0,3);days.push(`<div class="day ${day.getMonth()!==m?'other':''} ${key===todayKey()?'today':''}"><span class="day-num">${day.getDate()}</span>${ev.map(x=>`<span class="day-event" title="${esc(x.title)}">${ICONS[x.type]||'•'} ${esc(x.title)}</span>`).join('')}</div>`)}return `${pageHead('Kalender','Monatsübersicht',`<div class="calendar-controls"><button class="secondary" id="calPrev">←</button><strong>${new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(d)}</strong><button class="secondary" id="calNext">→</button></div>`)}<section class="card"><div class="calendar"><div class="dow">Mo</div><div class="dow">Di</div><div class="dow">Mi</div><div class="dow">Do</div><div class="dow">Fr</div><div class="dow">Sa</div><div class="dow">So</div>${days.join('')}</div></section>`}
function renderDocuments(){const entries=visibleEntries().filter(e=>['document','text'].includes(e.type));return `${pageHead('Dokumente','Fotos, Dateien und Textdokumente','<button class="primary" data-quick="document">＋ Dokument</button>')}<section class="card"><div class="list">${entries.map(entryRow).join('')||'<div class="empty">Noch keine Dokumente gespeichert.</div>'}</div></section>`}
function renderProjects(){return `${pageHead('Projekte','Zusammengehörige Inhalte als digitale Akten','<button class="primary" id="newProject">＋ Projekt</button>')}<div class="grid project-grid">${state.projects.map(p=>{const count=visibleEntries().filter(e=>e.projectId===p.id).length;return `<section class="card project-card"><h2>${esc(p.name)}</h2><p class="muted">${esc(p.description||'')}</p><strong>${count}</strong> Einträge<br><small>${esc(p.status||'aktiv')}</small></section>`}).join('')||'<div class="card empty">Noch keine Projekte.</div>'}</div>`}
function renderChronology(){return `${pageHead('Chronologie','Was wann passiert ist')}<section class="card"><div class="list">${chronologyEntries().slice(0,80).map(entryRow).join('')||'<div class="empty">Noch keine Chronologie.</div>'}</div></section>`}
function renderSearch(){return `${pageHead('Suche','Titel, Texte, Kategorien, Projekte und Tags lokal durchsuchen')}<section class="card"><label>Suchbegriff<input id="searchInput" type="search" placeholder="z. B. Versicherung"></label><div id="searchResults" class="list" style="margin-top:16px"></div></section>`}
function renderAudio(){const localSupport=offlineSpeechSupport();return `${pageHead('Audio & Live-Diktat','Aufnehmen, lokal speichern und – wenn verfügbar – vollständig lokal transkribieren')}<div class="grid dashboard-grid"><section class="card span-6"><h2>Audio-Memo</h2><div class="audio-box"><button id="recordAudio" class="record-button" aria-label="Audioaufnahme starten">●</button><strong id="recordStatus">Bereit</strong><p class="muted">Audio bleibt auf diesem Gerät.</p></div></section><section class="card span-6"><h2>Offline-Live-Diktat</h2><div class="audio-box"><button id="recordDictation" class="record-button" aria-label="Offline-Diktat starten">🎤</button><strong id="dictationStatus">${localSupport?'Lokale Spracherkennung erkannt':'Lokale Browser-Spracherkennung nicht verfügbar'}</strong><div id="dictationText" class="dictation-text" role="status" aria-live="polite">${localSupport?'Hier erscheint dein Text. Es wird kein Cloud-Fallback verwendet.':'Audio-Memos funktionieren trotzdem offline. Für universelles Offline-Diktat folgt die native whisper.cpp-Brücke.'}</div><button id="saveDictation" class="primary" hidden>✓ Diktat speichern</button></div></section><section class="card span-12"><h2>Gespeicherte Aufnahmen</h2><div class="list">${visibleEntries().filter(e=>['audio','dictation'].includes(e.type)).map(entryRow).join('')||'<div class="empty">Noch keine Aufnahme.</div>'}</div></section></div>`}

function renderSettings(){const theme=document.documentElement.dataset.theme,scale=document.documentElement.dataset.scale;return `${pageHead('Einstellungen & Diagnose','Lesbarkeit, Offline-Status und Datensicherung')}<div class="grid dashboard-grid"><section class="card span-6"><h2>Farbtheme</h2><div class="theme-grid">${[['hell','Klar & Hell'],['dunkel','Dunkel Kontrast'],['kontrast','Barrierefrei Kontrast'],['violett','Elegant Violett']].map(([v,l])=>`<button class="theme-button ${theme===v?'active':''}" data-theme-set="${v}">${l}</button>`).join('')}</div><h2 style="margin-top:22px">Schrift & Sichtbarkeit</h2><label>Profil<select id="scaleSelect"><option value="kompakt">Kompakt</option><option value="standard">Standard</option><option value="gross">Groß</option><option value="sehr-gross">Sehr groß</option><option value="maximal">Maximale Lesbarkeit</option></select></label></section><section class="card span-6"><h2>Backup</h2><p>Exportiert lokale Metadaten, Projekte und Einstellungen als JSON. Binäre Dokumente/Audio werden in 0.2.x in ein vollständiges Backup-Paket aufgenommen.</p><div class="two-col"><button class="secondary" id="exportBackup">⬇ Backup exportieren</button><label class="secondary" style="display:grid;place-items:center">⬆ Backup importieren<input id="importBackup" type="file" accept="application/json" hidden></label></div><h2 style="margin-top:22px">Diagnose</h2><div class="diag"><div class="diag-item"><strong>IndexedDB</strong><div class="ok">✓ aktiv</div></div><div class="diag-item"><strong>Offline-Kern</strong><div class="ok">✓ aktiv</div></div><div class="diag-item"><strong>Mikrofon</strong><div>${navigator.mediaDevices?.getUserMedia?'<span class="ok">✓ unterstützt</span>':'<span class="warn">⚠ nicht verfügbar</span>'}</div></div><div class="diag-item"><strong>Offline-Diktat</strong><div>${offlineSpeechSupport()?'<span class="ok">✓ On-Device API erkannt</span>':'<span class="warn">⚠ whisper.cpp folgt</span>'}</div></div></div></section><section class="card span-12"><h2>Version</h2><p><strong>PROVOWARE – NAQYA Memo Tool 2026 ${VERSION}</strong><br><span class="muted">OFFLINE FUNDAMENT PRO</span></p></section></div>`}

function render(){const v=$('#view');if(!v)return;const map={dashboard:renderDashboard,today:renderToday,calendar:renderCalendar,documents:renderDocuments,projects:renderProjects,audio:renderAudio,chronology:renderChronology,search:renderSearch,settings:renderSettings};v.innerHTML=(map[state.view]||renderDashboard)();$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));wireDynamic();}
function setView(v){state.view=v;render();$('#hauptinhalt').focus();if(innerWidth<760)$('#sidebar').classList.remove('open')}

function wireDynamic(){ $$('[data-quick]').forEach(b=>b.onclick=()=>openWizard(b.dataset.quick));$$('[data-view-go]').forEach(b=>b.onclick=()=>setView(b.dataset.viewGo));$('#calPrev')?.addEventListener('click',()=>{state.calendarDate=new Date(state.calendarDate.getFullYear(),state.calendarDate.getMonth()-1,1);render()});$('#calNext')?.addEventListener('click',()=>{state.calendarDate=new Date(state.calendarDate.getFullYear(),state.calendarDate.getMonth()+1,1);render()});$('#newProject')?.addEventListener('click',newProject);$('#recordAudio')?.addEventListener('click',toggleAudio);$('#recordDictation')?.addEventListener('click',toggleDictation);$('#saveDictation')?.addEventListener('click',saveDictation);$('#searchInput')?.addEventListener('input',e=>runSearch(e.target.value));$$('[data-theme-set]').forEach(b=>b.onclick=()=>setTheme(b.dataset.themeSet));const scale=$('#scaleSelect');if(scale){scale.value=document.documentElement.dataset.scale;scale.onchange=()=>setScale(scale.value)}$('#exportBackup')?.addEventListener('click',exportBackup);$('#importBackup')?.addEventListener('change',importBackup)}

function openWizard(type='note'){state.wizardStep=1;state.wizardType=type;$('#wizardForm').reset();$$('#typeGrid button').forEach(b=>b.classList.toggle('selected',b.dataset.type===type));syncWizard();loadProjectOptions();$('#wizard').showModal()}
function syncWizard(){$$('.wizard-step').forEach(x=>x.hidden=Number(x.dataset.step)!==state.wizardStep);$('#wizardStepLabel').textContent=`Schritt ${state.wizardStep} von 3`;$('#wizardProgress').style.width=`${state.wizardStep/3*100}%`;$('#wizardBack').disabled=state.wizardStep===1;$('#wizardNext').hidden=state.wizardStep===3;$('#wizardSave').hidden=state.wizardStep!==3;$('#fileLabel').hidden=state.wizardType!=='document';$('#wizardMessage').textContent=''}
function loadProjectOptions(){const s=$('#entryProject');s.innerHTML='<option value="">Noch keinem Projekt zuordnen</option>'+state.projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}
async function saveWizard(){const file=$('#entryFile').files?.[0];let fileId=null;if(file){fileId=uid();await put('files',{id:fileId,name:file.name,type:file.type,size:file.size,blob:file,createdAt:new Date().toISOString()})}const entry={id:uid(),type:state.wizardType,title:$('#entryTitle').value.trim()||LABELS[state.wizardType],text:$('#entryText').value.trim(),date:$('#entryDate').value?new Date($('#entryDate').value).toISOString():new Date().toISOString(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),priority:$('#entryPriority').value,status:'aktiv',projectId:$('#entryProject').value,category:$('#entryCategory').value.trim(),tags:$('#entryTags').value.split(',').map(x=>x.trim()).filter(Boolean),fileIds:fileId?[fileId]:[],deleted:false};await put('entries',entry);await logEvent('Eintrag erstellt',entry);$('#wizard').close();await refresh()}

async function newProject(){const name=prompt('Projektname:');if(!name?.trim())return;const description=prompt('Kurze Beschreibung (optional):')||'';const p={id:uid(),name:name.trim(),description,status:'aktiv',createdAt:new Date().toISOString()};await put('projects',p);await logEvent('Projekt erstellt',{...p,type:'project',title:p.name});await refresh()}

async function getAudioStream(){return navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,channelCount:1}})}
async function toggleAudio(){const btn=$('#recordAudio'),status=$('#recordStatus');if(state.recorder?.state==='recording'){state.recorder.stop();btn.classList.remove('active');status.textContent='Speichere …';return}try{const stream=await getAudioStream();state.audioChunks=[];state.recorder=new MediaRecorder(stream);state.recorder.ondataavailable=e=>{if(e.data.size)state.audioChunks.push(e.data)};state.recorder.onstop=async()=>{const blob=new Blob(state.audioChunks,{type:state.recorder.mimeType||'audio/webm'});const fileId=uid();await put('files',{id:fileId,name:`audio-${Date.now()}.webm`,type:blob.type,size:blob.size,blob,createdAt:new Date().toISOString()});const entry={id:uid(),type:'audio',title:`Audio-Memo ${new Intl.DateTimeFormat('de-DE',{dateStyle:'short',timeStyle:'short'}).format(new Date())}`,text:'',date:new Date().toISOString(),createdAt:new Date().toISOString(),status:'aktiv',priority:'normal',tags:[],fileIds:[fileId],deleted:false};await put('entries',entry);await logEvent('Audio-Memo gespeichert',entry);stream.getTracks().forEach(t=>t.stop());state.recorder=null;await refresh()};state.recorder.start(3000);btn.classList.add('active');status.textContent='Aufnahme läuft – erneut drücken zum Stoppen'}catch(e){status.textContent=`Mikrofon nicht verfügbar: ${e.message}`}}

function speechCtor(){return window.SpeechRecognition||window.webkitSpeechRecognition}
function offlineSpeechSupport(){const C=speechCtor();if(!C)return false;try{return 'processLocally' in C.prototype||'processLocally' in new C()}catch{return false}}
async function toggleDictation(){const btn=$('#recordDictation'),status=$('#dictationStatus');if(state.dictationRecognition){state.dictationRecognition.stop();state.dictationRecorder?.stop();btn.classList.remove('active');status.textContent='Diktat beendet';state.dictationRecognition=null;$('#saveDictation').hidden=false;return}if(!offlineSpeechSupport()){status.textContent='Keine lokale Browser-STT verfügbar. Kein Cloud-Fallback gestartet.';return}try{const C=speechCtor(),r=new C();r.lang='de-DE';r.continuous=true;r.interimResults=true;r.processLocally=true;state.dictationFinal='';state.dictationInterim='';r.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)state.dictationFinal+=t+' ';else interim+=t}state.dictationInterim=interim;$('#dictationText').textContent=(state.dictationFinal+interim).trim()};r.onerror=e=>{status.textContent=`Lokale Erkennung: ${e.error}. Kein Cloud-Fallback.`};r.onend=()=>{if(state.dictationRecognition===r){state.dictationRecognition=null;btn.classList.remove('active');$('#saveDictation').hidden=false}};const stream=await getAudioStream();state.dictationChunks=[];state.dictationRecorder=new MediaRecorder(stream);state.dictationRecorder.ondataavailable=e=>{if(e.data.size)state.dictationChunks.push(e.data)};state.dictationRecorder.onstop=()=>stream.getTracks().forEach(t=>t.stop());state.dictationRecorder.start(3000);state.dictationRecognition=r;r.start();btn.classList.add('active');status.textContent='Live-Diktat läuft vollständig lokal'}catch(e){status.textContent=`Lokales Diktat konnte nicht starten: ${e.message}`}}
async function saveDictation(){const text=(state.dictationFinal+state.dictationInterim).trim();if(!text&&!state.dictationChunks.length)return;let fileIds=[];if(state.dictationChunks.length){const blob=new Blob(state.dictationChunks,{type:state.dictationRecorder?.mimeType||'audio/webm'});const fileId=uid();await put('files',{id:fileId,name:`diktat-${Date.now()}.webm`,type:blob.type,size:blob.size,blob,createdAt:new Date().toISOString()});fileIds=[fileId]}const entry={id:uid(),type:'dictation',title:text.slice(0,70)||'Diktat',text,date:new Date().toISOString(),createdAt:new Date().toISOString(),status:'aktiv',priority:'normal',tags:['diktat'],fileIds,deleted:false};await put('entries',entry);await logEvent('Diktat gespeichert',entry);state.dictationChunks=[];state.dictationFinal='';state.dictationInterim='';await refresh()}

function runSearch(q){const out=$('#searchResults');if(!out)return;const s=q.trim().toLowerCase();if(!s){out.innerHTML='<div class="empty">Suchbegriff eingeben.</div>';return}const projectMap=new Map(state.projects.map(p=>[p.id,p.name]));const found=visibleEntries().filter(e=>[e.title,e.text,e.category,(e.tags||[]).join(' '),projectMap.get(e.projectId)||''].join(' ').toLowerCase().includes(s));out.innerHTML=found.map(entryRow).join('')||'<div class="empty">Keine Treffer.</div>'}

async function setTheme(theme){document.documentElement.dataset.theme=theme;await put('settings',{key:'theme',value:theme});render()}
async function setScale(scale){document.documentElement.dataset.scale=scale;await put('settings',{key:'scale',value:scale})}
async function loadSettings(){const theme=await get('settings','theme'),scale=await get('settings','scale');document.documentElement.dataset.theme=theme?.value||'hell';document.documentElement.dataset.scale=scale?.value||'standard'}

async function exportBackup(){const payload={schema:1,product:'PROVOWARE – NAQYA Memo Tool 2026',version:VERSION,exportedAt:new Date().toISOString(),entries:await all('entries'),projects:await all('projects'),settings:await all('settings')};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`NAQYA_BACKUP_${todayKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importBackup(e){const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data.schema!==1||!Array.isArray(data.entries))throw new Error('Unbekanntes Backupformat');for(const x of data.entries)await put('entries',x);for(const x of data.projects||[])await put('projects',x);for(const x of data.settings||[])await put('settings',x);await refresh();alert('Backup wurde eingelesen.')}catch(err){alert(`Import fehlgeschlagen: ${err.message}`)}}

function updateConnectivity(){const b=$('#offlineBadge');if(!b)return;b.textContent=navigator.onLine?'● lokal · Netz verfügbar':'● vollständig offline';b.classList.toggle('online',navigator.onLine)}
function assistant(text){$('#assistantContent').innerHTML=text}

async function init(){if(!('indexedDB'in window)){document.body.innerHTML='<main><h1>NAQYA kann nicht starten</h1><p>Dieser Browser unterstützt IndexedDB nicht.</p></main>';return}db=await openDB();await seed();await loadSettings();await refresh();$$('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#quickAdd').onclick=()=>openWizard('note');$('#navToggle').onclick=()=>$('#sidebar').classList.toggle('open');$('#openHelp').onclick=()=>$('#helpDialog').showModal();$('#globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){setView('search');setTimeout(()=>{const i=$('#searchInput');i.value=e.target.value;runSearch(i.value);i.focus()},0)}});$$('#typeGrid button').forEach(b=>b.onclick=()=>{state.wizardType=b.dataset.type;$$('#typeGrid button').forEach(x=>x.classList.toggle('selected',x===b));assistant(`<strong>${ICONS[state.wizardType]} ${LABELS[state.wizardType]}</strong><p>Im nächsten Schritt erfasst du nur die wichtigsten Angaben. Alles Weitere bleibt optional.</p>`)});$('#wizardBack').onclick=()=>{state.wizardStep=Math.max(1,state.wizardStep-1);syncWizard()};$('#wizardNext').onclick=()=>{state.wizardStep=Math.min(3,state.wizardStep+1);syncWizard()};$('#wizardSave').onclick=saveWizard;window.addEventListener('online',updateConnectivity);window.addEventListener('offline',updateConnectivity);updateConnectivity();if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('./sw.js')}catch(e){console.warn('Service Worker:',e)}}}

document.addEventListener('DOMContentLoaded',()=>init().catch(e=>{console.error(e);document.body.insertAdjacentHTML('afterbegin',`<div class="message">Startfehler: ${esc(e.message)}</div>`)}));
